### ISSUE TITLE
Need to get base64 url

### ISSUE THREAD

**Issue by Vigneshjana** [weihanchen/ng2-screenshot#1]
Need to get cropped area as base64 url in my component. Is it possible

**Comment by weihanchen** [comment]
it is possible, you can try [advance-usage](https://weihanchen.github.io/ng2-screenshot/#/examples/advance-usage#print)
Checkout `Print selected section` demo and use like:

```javascript
this.api.toPng((dataUrl: string) => {
   console.log(dataUrl);
  ...
}
```

**Comment by Vigneshjana** [comment]
Yes , Got it Thanks
