### ISSUE TITLE
'nz-switch' is not a known element:

### ISSUE THREAD

**Issue by spc2020** [weihanchen/ng2-screenshot#5]
I have installed all required package ng2-screenshot and dom-to-image but still showing error , compiler.js:2430 Uncaught Error: Template parse errors:
'nz-switch' is not a known element:

**Comment by spc2020** [comment]
Your suggestion would be highly appreciated.

**Comment by weihanchen** [comment]
`nz-switch` is part of [ng-zorro-antd](https://ng.ant.design/components/switch/en), the necessary installation of the demo, not related to ng2-screenshot
